. activate FSCA
cd /code/TimeLLM/code/ICLR25-FSCA-official/Classification

# Japels
CUDA_VISIBLE_DEVICES=0 python src/main_gnn_fsca.py --wd_project fsca-cla-log00 --batch_size=64 --comment="classification from Scratch" --d_ff=512 --d_l_comp=512 --d_model=768 --data_class=tsra --dropout=0.1 --epochs=120 --key_metric=accuracy --layer_index=4*0_1_4*0_1_4 --lr=0.001 --model=FSCA --name=JapaneseVowels --optimizer=RAdam --output_dir=experiments/ --patch_size_stride="4 2" --pattern=TRAIN --pos_encoding=learnable --records_file=Classification_records.xls --revin_flag=0 --seed=42 --task=classification --test_flag=0 --val_interval=1 --val_pattern=TEST --w_l2s_flag=0 --w_l2s_v=0.0001 --wandb_flag=1

# EthanolConcentration
CUDA_VISIBLE_DEVICES=0 python src/main_gnn_fsca.py --wd_project fsca-cla-log00 --batch_size=32 --comment="classification from Scratch" --d_ff=512 --d_l_comp=512 --d_model=768 --data_class=tsra --dropout=0.1 --epochs=100 --key_metric=accuracy --layer_index=4*0_1_4*0_1_4 --lr=0.01 --model=FSCA --name=EthanolConcentration --optimizer=RAdam --output_dir=experiments/ --patch_size_stride="64 64" --pattern=TRAIN --pos_encoding=learnable --records_file=Classification_records.xls --revin_flag=0 --seed=42 --task=classification --test_flag=0 --val_interval=1 --val_pattern=TEST --w_l2s_flag=0 --w_l2s_v=0.0001 --wandb_flag=1

# SpokenArabicDigits
CUDA_VISIBLE_DEVICES=0 python src/main_gnn_fsca.py --wd_project fsca-cla-log00 --batch_size=64 --comment="classification from Scratch" --d_ff=512 --d_l_comp=512 --d_model=768 --data_class=tsra --dropout=0.1 --epochs=120 --key_metric=accuracy --layer_index=4*0_4*0_4 --lr=0.001 --model=FSCA --name=SpokenArabicDigits --optimizer=RAdam --output_dir=experiments/ --patch_size_stride="8 4" --pattern=TRAIN --pos_encoding=learnable --records_file=Classification_records.xls --revin_flag=0 --seed=42 --task=classification --test_flag=0 --val_interval=1 --val_pattern=TEST --w_l2s_flag=0 --w_l2s_v=0.0001 --wandb_flag=1

# PEMS-SF
CUDA_VISIBLE_DEVICES=0 python src/main_gnn_fsca.py --wd_project fsca-cla-log00 --batch_size=64 --comment="classification from Scratch" --d_ff=512 --d_l_comp=512 --d_model=768 --data_class=tsra --dropout=0.1 --epochs=120 --key_metric=accuracy --layer_index=4*0_4*0_4 --lr=0.01 --model=FSCA --name=PEMS-SF --optimizer=RAdam --output_dir=experiments/ --patch_size_stride="8 8" --pattern=TRAIN --pos_encoding=learnable --records_file=Classification_records.xls --revin_flag=0 --seed=42 --task=classification --test_flag=0 --val_interval=1 --val_pattern=TEST --w_l2s_flag=0 --w_l2s_v=0.0001 --wandb_flag=1

# UWaveGestureLibrary
CUDA_VISIBLE_DEVICES=0 python src/main_gnn_fsca.py --wd_project fsca-cla-log00 --batch_size=64 --comment="classification from Scratch" --d_ff=512 --d_l_comp=512 --d_model=768 --data_class=tsra --dropout=0.1 --epochs=120 --key_metric=accuracy --layer_index=4*0_4*0_4 --lr=0.001 --model=FSCA --name=UWaveGestureLibrary --optimizer=RAdam --output_dir=experiments/ --patch_size_stride="64 32" --pattern=TRAIN --pos_encoding=learnable --records_file=Classification_records.xls --revin_flag=0 --seed=42 --task=classification --test_flag=0 --val_interval=1 --val_pattern=TEST --w_l2s_flag=0 --w_l2s_v=0.0001 --wandb_flag=1

# Handwriting
CUDA_VISIBLE_DEVICES=0 python src/main_gnn_fsca.py --wd_project fsca-cla-log00 --batch_size=64 --comment="classification from Scratch" --d_ff=512 --d_l_comp=512 --d_model=768 --data_class=tsra --dropout=0.1 --epochs=120 --key_metric=accuracy --layer_index=4*0_4*0_4 --lr=0.001 --model=FSCA --name=Handwriting --optimizer=RAdam --output_dir=experiments/ --patch_size_stride="8 4" --pattern=TRAIN --pos_encoding=learnable --records_file=Classification_records.xls --revin_flag=0 --seed=42 --task=classification --test_flag=0 --val_intervaneseVowal=1 --val_pattern=TEST --w_l2s_flag=0 --w_l2s_v=0.0001 --wandb_flag=1

# SelfRegulationSCP1 VCA
CUDA_VISIBLE_DEVICES=0 python src/main_gnn_vca.py --wd_project fsca-cla-log00 --batch_size=64 --comment="classification from Scratch" --d_ff=512 --d_l_comp=512 --d_model=768 --data_class=tsra --dropout=0.1 --epochs=120 --key_metric=accuracy --layer_index=4*0_1_4*0_1_4 --lr=0.01 --model=FSCA --name=SelfRegulationSCP1 --optimizer=RAdam --output_dir=experiments/ --patch_size_stride="64 32" --pattern=TRAIN --pos_encoding=learnable --records_file=Classification_records.xls --revin_flag=0 --seed=42 --task=classification --test_flag=0 --val_interval=1 --val_pattern=TEST --w_l2s_flag=0 --w_l2s_v=0.0001 --wandb_flag=1

# SelfRegulationSCP2 VCA
CUDA_VISIBLE_DEVICES=0 python src/main_gnn_vca.py --wd_project fsca-cla-log00 --batch_size=64 --comment="classification from Scratch" --d_ff=512 --d_l_comp=512 --d_model=768 --data_class=tsra --dropout=0.1 --epochs=120 --key_metric=accuracy --layer_index=4*0_1_4*0_1_4 --lr=0.0001 --model=FSCA --name=SelfRegulationSCP2 --optimizer=RAdam --output_dir=experiments/ --patch_size_stride="64 64" --pattern=TRAIN --pos_encoding=learnable --records_file=Classification_records.xls --revin_flag=0 --seed=42 --task=classification --test_flag=0 --val_interval=1 --val_pattern=TEST --w_l2s_flag=0 --w_l2s_v=0.0001 --wandb_flag=1

# Heartbeat VCA
CUDA_VISIBLE_DEVICES=0 python src/main_gnn_vca.py --wd_project fsca-cla-log00 --batch_size=64 --comment="classification from Scratch" --d_ff=512 --d_l_comp=512 --d_model=768 --data_class=tsra --dropout=0.1 --epochs=120 --key_metric=accuracy --layer_index=4*0_1_4*0_1_4 --lr=0.001 --model=FSCA --name=Heartbeat --optimizer=RAdam --output_dir=experiments/ --patch_size_stride="64 32" --pattern=TRAIN --pos_encoding=learnable --records_file=Classification_records.xls --revin_flag=0 --seed=42 --task=classification --test_flag=0 --val_interval=1 --val_pattern=TEST --w_l2s_flag=0 --w_l2s_v=0.0001 --wandb_flag=1

# FaceDetection VCA
CUDA_VISIBLE_DEVICES=0 python src/main_gnn_vca.py --wd_project fsca-cla-log00 --batch_size=64 --comment="classification from Scratch" --d_ff=512 --d_l_comp=768 --d_model=768 --data_class=tsra --dropout=0.1 --epochs=30 --key_metric=accuracy --layer_index=4*0*0 --lr=5e-05 --model=FSCA --name=FaceDetection --optimizer=RAdam --output_dir=experiments/ --patch_size_stride="8 1" --pattern=TRAIN --pos_encoding=learnable --records_file=Classification_records.xls --revin_flag=0 --seed=42 --task=classification --test_flag=0 --val_interval=1 --val_pattern=TEST --w_l2s_flag=0 --w_l2s_v=0.0001 --wandb_flag=1